config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :speakers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  link        :string
#  date        :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Event < ActiveRecord::Base
  has_many :event_speakers
  has_many :speakers, through: :event_speakers

  scope :upcoming, -> { last }
  scope :last_occurred, -> { last }
end

app/models/event_speaker.rb
# == Schema Information
#
# Table name: event_speakers
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  speaker_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_event_speakers_on_event_id    (event_id)
#  index_event_speakers_on_speaker_id  (speaker_id)
#
class EventSpeaker < ActiveRecord::Base
  belongs_to :event
  belongs_to :speaker
end

app/models/speaker.rb
# == Schema Information
#
# Table name: speakers
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  twitter    :string
#  github     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Speaker < ActiveRecord::Base
  has_many :event_speakers
  has_many :events, through: :event_speakers
end

app/controllers/application_controller.rb
# Sitewide base controller class
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_action
    params[:action]
  end
end

app/controllers/concerns/eventable.rb
# Handles CRUD actions for all Events
module Eventable
  extend ActiveSupport::Concern

  private

  def event_params
    params.require(:event).permit!
  end

  def speakers_for_events
    @events ||= all_speakers_for_events
  end

  def events
    @events ||= all_events
  end

  def event
    @event ||= (found_event || new_event || blank_event || nil)
  end

  def all_speakers_for_events
    actions = %w(new edit)
    return unless actions.include? current_action
    Speaker.all
  end

  def all_events
    actions = %w(index)
    return unless actions.include? current_action
    Event.all
  end

  def found_event
    actions = %w(show edit update destroy)
    return unless actions.include? current_action
    Event.find(params[:id])
  end

  def blank_event
    actions = %w(new)
    return unless actions.include? current_action
    Event.new
  end

  def new_event
    actions = %w(create)
    return unless actions.include? current_action
    Event.new event_params
  end
end

app/controllers/concerns/speakerable.rb
# Handles CRUD actions for all Events
module Speakerable
  extend ActiveSupport::Concern

  private

  def speaker_params
    params.require(:speaker).permit(:first_name, :last_name, :email, :twitter, :github)
  end

  def speakers
    @speakers ||= all_speakers
  end

  def speaker
    @event ||= (found_speaker || new_speaker || blank_speaker || nil)
  end

  def all_speakers
    actions = %w(index)
    return unless actions.include? current_action
    Speaker.all
  end

  def found_speaker
    actions = %w(show edit update destroy)
    return unless actions.include? current_action
    Speaker.find(params[:id])
  end

  def blank_speaker
    actions = %w(new)
    return unless actions.include? current_action
    Speaker.new
  end

  def new_speaker
    actions = %w(create)
    return unless actions.include? current_action
    Speaker.new speaker_params
  end
end

app/controllers/events_controller.rb
# Controller around handling the Event crud and display pages
class EventsController < ApplicationController
  include Eventable

  helper_method :events
  helper_method :event
  helper_method :speakers_for_events

  def index
  end

  def show
  end

  def new
  end

  def create
    if event.save
      flash[:notice] = 'Successfully created event'
    else
      flash[:success] = 'Failed to create event'
    end

    redirect_to events_path
  end

  def edit
  end

  def update
    if event.update_attributes event_params
      flash[:notice] = 'Successfully updated event'
    else
      flash[:success] = 'Failed to update event'
    end

    redirect_to events_path
  end

  def destroy
    if event.destroy
      flash[:notice] = 'Successfully destroyed event'
    else
      flash[:success] = 'Failed to destroy event'
    end

    redirect_to events_path
  end
end

app/controllers/home_controller.rb
# Controller for managing the homepage of the site
class HomeController < ApplicationController
  helper_method :last_meetup
  helper_method :upcoming_meetup

  def index
  end

  private

  def last_meetup
    @last_meetup ||= (Event.last_occurred || nil)
  end

  def upcoming_meetup
    @upcoming_meetup ||= (Event.upcoming || nil)
  end
end

app/controllers/speakers_controller.rb
# Controller around handling the Speaker crud and display pages
class SpeakersController < ApplicationController
  include Speakerable

  helper_method :speakers
  helper_method :speaker

  def index
  end

  def show
  end

  def new
  end

  def create
    if speaker.save
      flash[:notice] = 'Successfully created speaker'
    else
      flash[:error] = 'Failed to create speaker'
    end

    redirect_to speakers_path
  end

  def edit
  end

  def update
    if speaker.update_attributes speaker_params
      flash[:notice] = 'Successfully updated speaker'
    else
      flash[:error] = 'Failed to update speaker'
    end

    redirect_to speakers_path
  end

  def destroy
    if speaker.destroy
      flash[:notice] = 'Successfully destroyed speaker'
    else
      flash[:error] = 'Failed to destroy speaker'
    end

    redirect_to speakers_path
  end
end

app/helpers/application_helper.rb
# Sitewide base view helper module
module ApplicationHelper
end

app/helpers/user_helper.rb
# Module for all user like objects
module UserHelper
  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/views/events/_form.html.haml
.admin-page
  = form_for event do |f|
    %fieldset
      = f.label :name
      = f.text_field :name
    %fieldset
      = f.label :description
      = f.text_field :description
    %fieldset
      = f.label :link
      = f.text_field :link
    %fieldset
      = f.label :date
      = f.date_field :date
    %fieldset
      %p Speakers
      - speakers_for_events.each do |speaker|
        %div
          = check_box_tag :speaker_ids, speaker.id, event.speakers.include?(speaker), name: 'event[speaker_ids][]'
          = label_tag :speaker_ids, full_name(speaker)
    %fieldset
      = f.submit nil

app/views/events/edit.html.haml
.admin-page
  %h2 Edit Event
  = render partial: 'events/form'

app/views/events/index.html.haml
.admin-page
  %h2 Events
  = link_to 'New Event', new_event_path
  %table.tables
    %thead
      %tr
        %th{scope: 'col'} ID
        %th{scope: 'col'} Name
        %th{scope: 'col'} Description
        %th{scope: 'col'} Link
        %th{scope: 'col'} Date
        %th{scope: 'col'} Speakers
        %th{scope: 'col'} Created At
        %th{scope: 'col'} Updated At
        %th{scope: 'col'}
    %tbody
      - events.each do |event|
        %tr
          %td= event.id
          %td= event.name
          %td= event.description
          %td= event.link
          %td= event.date
          %td
            %ul
            - event.speakers.each do |speaker|
              %li= full_name speaker
          %td= event.created_at
          %td= event.updated_at
          %td
            = link_to 'show', event_path(event.id)
            = link_to 'edit', edit_event_path(event.id)
            = link_to 'delete', event_path(event.id), method: :delete

app/views/events/new.html.haml
.admin-page
  %h2 New Event
  = render partial: 'events/form'

app/views/events/show.html.haml
.admin-page
  %h2 Event
  %h3= event.name
  = link_to 'edit', edit_event_path(event.id)
  = link_to 'delete', event_path(event.id), method: :delete
  %ul
    %li= event.description
    %li
      = link_to 'meetup', event.link
    %li= "Date: #{event.date}"
    %li= "Created At: #{event.created_at}"
    %li= "Updated At: #{event.updated_at}"

  %h4 Speakers
  %ul
    - event.speakers.each do |speaker|
      %li= full_name speaker

app/views/home/index.html.haml
.home-page
  = render partial: 'refills/hero'
  %section.last
    %article
      %h1 Last Meetup
      %h2= last_meetup.name
      %p= last_meetup.date
      - last_meetup.speakers.each do |speaker|
        %p= full_name speaker
      %h3 Description
      %p= last_meetup.description

  %section.upcoming
    %article
      %h1 Next Meetup
      %h2= upcoming_meetup.name
      %p= last_meetup.date
      - upcoming_meetup.speakers.each do |speaker|
        %p= full_name speaker
      %h3 Description
      %p= upcoming_meetup.description

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title SoftwareTestingMeetup
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render partial: 'refills/navigation'
    = render partial: 'shared/flash'
    = yield
    = render partial: 'refills/footer'

app/views/refills/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

  <hr>

  <p>Disclaimer area lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, nostrum repudiandae saepe.</p>
</footer>

app/views/refills/_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png
" alt="Logo Image"></a>
		<div class="hero-copy">
			<h1>Orlando Software Testing Meetup</h1>
			<p>Networking . QA . Automation</p>
		</div>
	</div>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to 'Home', root_path %></li>
        <li class="nav-link"><%= link_to 'Events', events_path %></li>
        <li class="nav-link"><%= link_to 'Speakers', speakers_path %></li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <a href="javascript:void(0)" class="sign-up">Sign Up</a>
    </div>
  </div>
</header>

app/views/shared/_flash.html.haml
- if flash[:error]
  = flash[:error]
- if flash[:notice]
  = flash[:notice]

app/views/speakers/_form.html.haml
= form_for speaker do |f|
  %fieldset
    = f.label :first_name
    = f.text_field :first_name
  %fieldset
    = f.label :last_name
    = f.text_field :last_name
  %fieldset
    = f.label :email
    = f.text_field :email
  %fieldset
    = f.label :twitter
    = f.text_field :twitter
  %fieldset
    = f.label :github
    = f.text_field :github
  %fieldset
    = f.submit nil

app/views/speakers/edit.html.haml
.admin-page
  %h2 Edit Speaker
  = render partial: 'speakers/form'

app/views/speakers/index.html.haml
.admin-page
  %h2 Speakers
  = link_to 'New Speaker', new_speaker_path
  %table.tables
    %thead
      %tr
        %th{scope: 'col'} ID
        %th{scope: 'col'} First Name
        %th{scope: 'col'} Last Name
        %th{scope: 'col'} Email
        %th{scope: 'col'} Twitter
        %th{scope: 'col'} Github
        %th{scope: 'col'} Created At
        %th{scope: 'col'} Updated At
        %th{scope: 'col'}
    %tbody
      - speakers.each do |speaker|
        %tr
          %td= speaker.id
          %td= speaker.first_name
          %td= speaker.last_name
          %td= speaker.email
          %td= speaker.twitter
          %td= speaker.github
          %td= speaker.created_at
          %td= speaker.updated_at
          %td
            = link_to 'show', speaker_path(speaker.id)
            = link_to 'edit', edit_speaker_path(speaker.id)
            = link_to 'delete', speaker_path(speaker.id), method: :delete

app/views/speakers/new.html.haml
.admin-page
  %h2 New Speaker
  = render partial: 'speakers/form'

app/views/speakers/show.html.haml
.admin-page
  %h2 Speaker
  %h3= full_name speaker
  = link_to 'edit', edit_speaker_path(speaker.id)
  = link_to 'delete', speaker_path(speaker.id), method: :delete
  %ul
    %li= speaker.email
    %li= link_to 'github', speaker.github
    %li= link_to 'twitter', speaker.twitter
    %li= "Created At: #{speaker.created_at}"
    %li= "Updated At: #{speaker.updated_at}"